# Generated by Django 5.0.6 on 2024-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProduct', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueDate', models.DateField()),
                ('kindOfProduct', models.CharField(choices=[('B', 'Bebidas'), ('S', 'Snacks'), ('F', 'Frutas'), ('P', 'Peluches'), ('G', 'Golosinas'), ('O', 'Otro')], max_length=2)),
            ],
        ),
    ]
